---
- name: Create the Node Exporter group
  group:
    name: "node-exp"
    state: present
    system: yes

- name: Create the Node Exporter user
  user:
    name: "node-exp"
    groups: "node-exp"
    append: yes
    shell: /usr/sbin/nologin
    system: yes
    createhome: no

- name: Download node exporter binary to local folder
  become: no
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
  run_once: true
  delegate_to: localhost

- name: Propagate Node Exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/opt/node_exporter"
    mode: 0755
    owner: "node-exp"
    group: "node-exp"
  notify:
    - restart node_exporter

- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter

- name: Ensure Node Exporter is enabled on boot
  service:
    name: node_exporter
    enabled: yes
